# Generated by Django 5.1.3 on 2024-11-26 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Valor en grados, entre -180.0 y 180.0.', max_digits=9, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Valor en grados, entre -90.0 y 90.0.', max_digits=9, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Temperatura en grados Celsius, entre -50 y 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(100)])),
                ('humidity', models.DecimalField(decimal_places=2, help_text='Porcentaje de humedad, entre 0 y 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pressure', models.DecimalField(decimal_places=2, help_text='Presión en hPa, entre 300 y 1100.', max_digits=7, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(1100)])),
                ('altitude', models.DecimalField(decimal_places=2, help_text='Altitud en metros, entre -500 y 9000.', max_digits=7, validators=[django.core.validators.MinValueValidator(-500), django.core.validators.MaxValueValidator(9000)])),
                ('timestamp', models.BigIntegerField(help_text='Tiempo en formato UNIX (número entero positivo).', validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
